"""Emit Lean certificate chunks from a verified #647 kill-chain ledger.

Each chunk file defines one witness list literal and proves one Bool
equality by `decide`:

    theorem chunkNNNN_ok : chainOk C_start chunkNNNN C_end = true := by decide

C_start / C_end are the exact cover positions the generator walked, so
adjacent chunks compose end to start. A driver file Cert.lean glues the
per-chunk covered intervals into the rung theorem via Chain.chain_sound.

Usage: python3 emit_lean.py chain.jsonl X outdir [chunk_size] [rung_tag]

With a rung_tag (e.g. "1e8"), the chunk namespace, driver file, and rung
theorem are suffixed so several rungs can coexist in one library.
"""

import json
import sys
from pathlib import Path

HEADER = """/-
Copyright (c) 2026 Millennium Research. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Millennium Research (Ibby Mian)
-/
import Erdos647.Defs

/-! Generated by scripts/emit_lean.py from a doubly-verified chain ledger.
Do not edit by hand. -/

namespace Erdos647.NAMESPACE

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

"""


def fmt_pairs(pairs: list[list[int]]) -> str:
    return "[" + ",".join(f"({p},{e})" for p, e in pairs) + "]"


def emit(chain_path: str, x: int, outdir: str, chunk_size: int = 4000,
         tag: str = "") -> None:
    suffix = f"_{tag}" if tag else ""
    ns = Path(outdir).name
    driver = "Cert" + (tag.replace("e", "E") if tag else "")
    out = Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    witnesses = []
    cover = 24
    covers = [cover]  # cover position before each witness
    with open(chain_path, encoding="utf-8") as f:
        for line in f:
            rec = json.loads(line)
            if rec["record"] != "witness":
                continue
            d, pairs = rec["d"], rec["pairs"]
            m = cover - d
            t = 1
            sv = 1
            for p_, e in pairs:
                t *= e + 1
                sv *= p_**e
            if sv < m:
                t *= 2
            cover = m + t - 3
            witnesses.append((d, pairs))
            covers.append(cover)
    assert cover >= x, (cover, x)

    chunks = []
    for i in range(0, len(witnesses), chunk_size):
        chunks.append((i, min(i + chunk_size, len(witnesses))))

    names = []
    for k, (i, j) in enumerate(chunks):
        name = f"chunk{k:04d}"
        names.append((name, covers[i], covers[j]))
        body = ",\n  ".join(
            f"({d},{fmt_pairs(ps)})" for d, ps in witnesses[i:j])
        text = (HEADER.replace("NAMESPACE", ns)
                + f"def {name} : List (ℕ × Pairs) := [\n  {body}]\n\n"
                + f"theorem {name}_ok : chainOk {covers[i]} {name} "
                + f"{covers[j]} = true := by decide\n\n"
                + f"end Erdos647.{ns}\n")
        (out / f"Chunk{k:04d}.lean").write_text(text, encoding="utf-8")

    imports = "\n".join(
        f"import Erdos647.{ns}.Chunk{k:04d}" for k in range(len(chunks)))
    cases = []
    for k, (name, ci, cj) in enumerate(names):
        cases.append(
            f"  rcases Nat.lt_or_ge {cj} n with h{k} | h{k}\n"
            if k + 1 < len(names) else "")
    # Build the rung theorem: n in (24, X] falls in exactly one chunk
    # interval (C_i, C_j]; apply chain_sound of that chunk.
    lines = [
        "/-", "Copyright (c) 2026 Millennium Research. All rights reserved.",
        "Released under Apache 2.0 license as described in the file LICENSE.",
        "Authors: Millennium Research (Ibby Mian)", "-/",
        imports, "import Erdos647.Chain", "",
        "set_option maxRecDepth 1000000",
        "set_option maxHeartbeats 0", "",
        "/-! Generated driver: composes the chunk certificates into the",
        f"rung theorem covering (24, {x}]. Do not edit by hand. -/", "",
        "namespace Erdos647", "",
        f"/-- Every `n` with `24 < n ≤ {x}` has a kill witness:",
        "the running maximum `max_{m<n}(m + τ(m))` reaches `n + 3`. -/",
        f"theorem killed_upto{suffix} (n : ℕ) (h24 : 24 < n) (hX : n ≤ {x}) :",
        "    Killed n := by",
    ]
    for k, (name, ci, cj) in enumerate(names):
        last = k + 1 == len(names)
        if not last:
            lines.append(f"  by_cases h{k} : n ≤ {cj}")
            lines.append(f"  · exact chain_sound {ns}.{name}_ok n "
                         f"(by omega) h{k}")
        else:
            lines.append(f"  exact chain_sound {ns}.{name}_ok n "
                         f"(by omega) (by omega)")
    lines += ["", "end Erdos647", ""]
    (out.parent / f"{driver}.lean").write_text("\n".join(lines),
                                               encoding="utf-8")
    print(f"emitted {len(chunks)} chunks, {len(witnesses)} witnesses, "
          f"final cover {cover}")


if __name__ == "__main__":
    emit(sys.argv[1], int(float(sys.argv[2])), sys.argv[3],
         int(sys.argv[4]) if len(sys.argv) > 4 else 4000,
         sys.argv[5] if len(sys.argv) > 5 else "")
